[tool.poetry]
name = "utils"
version = "0.1.0"
description = ""
authors = ["Court Schuett <schuettc@amazon.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "^1.33.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
